# Generated by Django 2.2 on 2020-05-19 02:28

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_image_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='result',
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(null=True, upload_to=detection.models.get_detection_image_path, verbose_name='推論用画像を選択'),
        ),
    ]
